#!/bin/env python3

import os
import fnmatch

FUNCTIONS_FILE="combined_functions.py"
HEADER="""
# DO NOT EDIT THIS FILE, IT IS A COMBINATION OF ALL THE FUNCTIONS IN THE functions/
# SUBDIRECTORY OF THIS REPOSITORY

from spike import PrimeHub, LightMatrix, Button, StatusLight, ForceSensor, MotionSensor, Speaker, ColorSensor, App, DistanceSensor, Motor, MotorPair
from spike.control import wait_for_seconds, wait_until, Timer
import math
import time
import hub
"""

with open(FUNCTIONS_FILE, 'w') as ff:
    ff.write(HEADER)

files=os.listdir('functions')
files.sort()

with open(FUNCTIONS_FILE, 'a') as ff:
    documentation_lines = []
    for function_filename in files:
        write_to_combined_file = False
        if fnmatch.fnmatch(function_filename, '*.py'):
            with open(f'functions/{function_filename}', 'r') as function_file:
                line = function_file.readline()
                ff.write(f"""

###
### BEGIN FUNCTION FROM FILE: {function_filename}
###

""")
                while line:                
                    if "FUNCTION START" in line:
                        write_to_combined_file = True
                    elif "FUNCTION END" in line:
                        write_to_combined_file = False
                    elif write_to_combined_file:
                        ff.write(line)
                    if write_to_combined_file and line.startswith('def '):
                        documentation_lines.append(f'({function_filename}) {line}')
                    line = function_file.readline()
    ff.write('\n###\n### FUNCTION DEFINITIONS\n###\n')
    for d in documentation_lines:
        ff.write(f'# {d}')