#!/bin/env python3

import os
import fnmatch

FUNCTIONS_FILE="combined_functions.py"
HEADER="""
# DO NOT EDIT THIS FILE, IT IS A COMBINATION OF ALL THE FUNCTIONS IN THE functions/
# SUBDIRECTORY OF THIS REPOSITORY

from spike import PrimeHub, LightMatrix, Button, StatusLight, ForceSensor, MotionSensor, Speaker, ColorSensor, App, DistanceSensor, Motor, MotorPair
from spike.control import wait_for_seconds, wait_until, Timer
import math
import time
import hub
"""

with open(FUNCTIONS_FILE, 'w') as f:
    f.write(HEADER)

files=os.listdir('functions').sort()
for file in files:
    if fnmatch.fnmatch(file, '*.py'):
        print(file)
